name: Test Workflow

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  list:
    name: 'List Repos'
    runs-on: [ubuntu-latest]
    outputs:
      matrix: ${{ steps.list.outputs.value }}
    steps:
      - name: 'Check out devops repo'
        uses: actions/checkout@v4.0.0
      - id: list
        name: 'List automerge repos'
        run: echo "value=$(cat test/automerge.json | tr -d '\n')" >> $GITHUB_OUTPUT
  
  automerge-test:
    name: 'Automerge'
    runs-on: [ubuntu-latest]
    needs: list
    strategy:
      fail-fast: false
      matrix:
        value: ${{fromJson(needs.list.outputs.matrix)}}
    steps:
      - name: 'Check Automerge Repo to Test'
        uses: actions/checkout@v4

      - name: 'Automerge runtimeverification/${{ matrix.value }}'
        uses: ./ # This uses the action in the root directory
        id: automerge
        with:
          org: 'runtimeverification'
          repo: ${{ matrix.value }}
          token: ${{ secrets.AUTOMERGE_TOKEN }}
          debug: --dry-run
           
      - name: 'Automerge runtimeverification/${{ matrix.value }}'
        uses: ./ # This uses the action in the root directory
        id: automerge-comment
        with:
          org: 'runtimeverification'
          repo: ${{ matrix.value }}
          token: ${{ secrets.AUTOMERGE_TOKEN }}
          debug: --dry-run
          comment: 'true'
             